### PR TITLE
Styling

### PR DESCRIPTION
**Pull request by JunChoii**
icons done

### CODE REVIEW

**Comment by M1xckk** [comment]
I like the svg icons, replace the arrow icon make it looks better

**Review by M1xckk — COMMENTED** [review]
looks good

**Comment by M1xckk** [comment]
icons looks good

**Review by M1xckk — COMMENTED** [review]
All good

**Review by FernandoDaumichen — COMMENTED** [review]
good =)

**Review by FernandoDaumichen — APPROVED** [review]
good to go

**Pull request merged**
